### ISSUE TITLE
ODK - skip questions

### ISSUE THREAD

**Issue by BertaOrtiz** [BioversityCostaRica/py3ClimMob#154]
when a field agent goes to the field to collect data about the trial one of the first questions is to ask whether the farmer has lost the plot or not. If the answer to this question is yes, the field agent keeps on seeing the rest of questions, which can generate confusion since they will run all of them through farmers. Would it be a way to not show any of the evaluation questions if the farmer has lost the plot?

**Comment by kauedesousa** [comment]
This will be solved when we implement this https://github.com/BioversityCostaRica/py3ClimMob/issues/129
